#!/usr/bin/env bash
# Build script for THE GRID native Android worker APK.
# v1.7.5 — supports two flavors:
#   FLAVOR=light    → Google Play / App Store safe.
#                     · package io.thegrid.light
#                     · NO librandomx.so (zero device-side mining)
#                     · AdMob test ID embedded in BuildConfig.java
#                     · output: grid-worker-light.apk
#   FLAVOR=nodepro  → Direct-download advanced client.
#                     · package io.thegrid.nodepro
#                     · embeds librandomx.so (device-side workloads)
#                     · NO AdMob SDK
#                     · output: grid-worker-nodepro.apk
#
# Honest CLI-only pipeline — no Gradle, no Android Studio.
set -euo pipefail

cd "$(dirname "$0")/wrapper"

SDK=/opt/android-sdk
# v1.6.5 — on ARM64 container hosts the Google-provided x86_64 build-tools
# binaries (aapt/zipalign/apksigner) won't execute; prefer Debian's apt-shipped
# native arm64 binaries from /usr/bin. The Google android.jar is arch-agnostic.
DEB_BT=/usr/bin
PLATFORM=$SDK/platforms/android-34/android.jar
D8_JAR=$SDK/build-tools/34.0.0/lib/d8.jar
VERSION="${VERSION:-1.7.5}"
FLAVOR="${FLAVOR:-nodepro}"

case "$FLAVOR" in
    light)   PKG="io.thegrid.light";   OUT_NAME="grid-worker-light.apk";   NATIVE_REQUIRED=0; ADMOB_ON=1 ;;
    nodepro) PKG="io.thegrid.nodepro"; OUT_NAME="grid-worker-nodepro.apk"; NATIVE_REQUIRED=1; ADMOB_ON=0 ;;
    *)       echo "[FATAL] Unknown FLAVOR='$FLAVOR' (expected: light | nodepro)" >&2; exit 2 ;;
esac
OUT_DEST="/app/frontend/public/${OUT_NAME}"

# v1.3.7 — bundle librandomx.so when the GitHub Actions artifact is present.
# Path: /app/android-client/wrapper/jniLibs/arm64-v8a/librandomx.so
JNI_DIR="$(pwd)/jniLibs"
NATIVE_LIB="${JNI_DIR}/arm64-v8a/librandomx.so"

rm -rf build/classes build/gen build/grid-*.apk build/classes.dex build/lib
mkdir -p build/classes build/gen

# v1.7.5 — write a flavor-aware AndroidManifest.xml each build so both APKs
# can co-exist on the same device with distinct package names.
VERSION_CODE="$(echo "$VERSION" | awk -F. '{ printf "%d%02d%02d", $1, $2, $3 }')"
APP_LABEL_LIGHT="THE GRID Light"
APP_LABEL_NODEPRO="THE GRID Node Pro"
case "$FLAVOR" in light) LABEL="$APP_LABEL_LIGHT" ;; *) LABEL="$APP_LABEL_NODEPRO" ;; esac

# Use a templated manifest if present, otherwise patch the existing one in-place.
if [ -f AndroidManifest.template.xml ]; then
    sed -e "s|@@PACKAGE@@|${PKG}|g" \
        -e "s|@@VERSION_CODE@@|${VERSION_CODE}|g" \
        -e "s|@@VERSION_NAME@@|${VERSION}|g" \
        -e "s|@@APP_LABEL@@|${LABEL}|g" \
        AndroidManifest.template.xml > AndroidManifest.xml
else
    sed -i -E "s|android:versionCode=\"[0-9]+\"|android:versionCode=\"${VERSION_CODE}\"|" AndroidManifest.xml
    sed -i -E "s|android:versionName=\"[^\"]+\"|android:versionName=\"${VERSION}\"|"     AndroidManifest.xml
    sed -i -E "s|package=\"[^\"]+\"|package=\"${PKG}\"|"                                  AndroidManifest.xml
fi
echo "[+] flavor=${FLAVOR} package=${PKG} version=${VERSION} versionCode=${VERSION_CODE}"

# v1.7.5 — generate BuildConfig.java carrying flavor + AdMob switch into the
# Java source tree so Java code can branch on it at compile time.
mkdir -p build/gen/io/thegrid/worker
cat > build/gen/io/thegrid/worker/BuildConfig.java <<EOF
package io.thegrid.worker;

/** Auto-generated by build-apk.sh — do not edit. */
public final class BuildConfig {
    private BuildConfig() {}
    public static final String FLAVOR         = "${FLAVOR}";
    public static final String VERSION_NAME   = "${VERSION}";
    public static final int    VERSION_CODE   = ${VERSION_CODE};
    public static final boolean ADMOB_ENABLED = $([ "$ADMOB_ON" -eq 1 ] && echo "true" || echo "false");
    public static final boolean NATIVE_MINING = $([ "$NATIVE_REQUIRED" -eq 1 ] && echo "true" || echo "false");
}
EOF

# 1. compile resources
$DEB_BT/aapt package -f -M AndroidManifest.xml -S res \
    -I "$PLATFORM" \
    -F build/grid-unaligned.apk -J build/gen
[ -f build/gen/R.java ] && mv build/gen/R.java build/gen/io/thegrid/worker/R.java || true

# 2. compile Java
javac -source 1.8 -target 1.8 -d build/classes \
    -cp "$PLATFORM" \
    src/io/thegrid/worker/*.java \
    build/gen/io/thegrid/worker/R.java \
    build/gen/io/thegrid/worker/BuildConfig.java

# 3. DEX
java -cp "$D8_JAR" com.android.tools.r8.D8 \
    --release --min-api 24 \
    --lib "$PLATFORM" \
    --output build/ $(find build/classes -name "*.class")

# 4. Add classes.dex to APK
cp build/grid-unaligned.apk build/grid-with-dex.apk
( cd build && zip -j -q grid-with-dex.apk classes.dex )

# 4b. Native library handling.
NATIVE_FLAG="OFF"
NATIVE_SHA="-"
if [ "$NATIVE_REQUIRED" -eq 1 ]; then
    if [ ! -f "$NATIVE_LIB" ]; then
        cat <<EOF >&2

[FATAL] Node Pro build aborted — librandomx.so missing.

Expected path:
    $NATIVE_LIB

Produce it via:
    1. Save to GitHub.
    2. Run the "build-librandomx-android-arm64" workflow.
    3. Download librandomx-arm64-v8a artifact, unzip into the path above.

EOF
        exit 99
    fi
    echo "[+] embedding librandomx.so ($(stat --format=%s "$NATIVE_LIB") bytes)"
    mkdir -p build/lib/arm64-v8a
    cp "$NATIVE_LIB" build/lib/arm64-v8a/librandomx.so
    ( cd build && zip -r -q grid-with-dex.apk lib )
    NATIVE_FLAG="ON"
    NATIVE_SHA=$(sha256sum build/lib/arm64-v8a/librandomx.so | cut -d' ' -f1)
    echo "[+] native lib SHA-256: $NATIVE_SHA"
else
    echo "[+] flavor=light — native library intentionally omitted"
fi

# 5. Align
$DEB_BT/zipalign -p -f 4 build/grid-with-dex.apk build/grid-aligned.apk

# 6. Sign with debug keystore (create if missing)
KS=build/debug.keystore
if [ ! -f "$KS" ]; then
    keytool -genkey -v \
        -keystore "$KS" \
        -storepass android -keypass android \
        -alias androiddebugkey -dname "CN=Android Debug,O=Android,C=US" \
        -keyalg RSA -keysize 2048 -validity 10000 >/dev/null 2>&1
fi

$DEB_BT/apksigner sign \
    --ks "$KS" --ks-key-alias androiddebugkey \
    --ks-pass pass:android --key-pass pass:android \
    --v1-signing-enabled true --v2-signing-enabled true --v3-signing-enabled true \
    --out "build/${OUT_NAME}" build/grid-aligned.apk

$DEB_BT/apksigner verify -v "build/${OUT_NAME}" >/dev/null
cp -f "build/${OUT_NAME}" "$OUT_DEST"

SIZE=$(stat --format=%s "$OUT_DEST")
SHA=$(sha256sum "$OUT_DEST" | cut -d' ' -f1)
echo
echo "=== APK BUILD OK ==="
echo "File   : $OUT_DEST"
echo "Flavor : $FLAVOR"
echo "Package: $PKG"
echo "Version: $VERSION"
echo "Native : $NATIVE_FLAG"
echo "AdMob  : $([ "$ADMOB_ON" -eq 1 ] && echo "ENABLED (test ID)" || echo "disabled")"
echo "Size   : $SIZE bytes"
echo "SHA-256: $SHA"
