#!/usr/bin/env bash
# Build script for THE GRID native Android worker APK.
# v1.7.5 — supports two flavors:
#   FLAVOR=light    → Google Play / App Store safe.
#                     · package io.sanctara.light
#                     · NO librandomx.so (zero device-side mining)
#                     · AdMob test ID embedded in BuildConfig.java
#                     · output: sanctara-light.apk
#   FLAVOR=nodepro  → Direct-download advanced client.
#                     · package io.sanctara.nodepro
#                     · embeds librandomx.so (device-side workloads)
#                     · NO AdMob SDK
#                     · output: sanctara-node-pro.apk
#
# Honest CLI-only pipeline — no Gradle, no Android Studio.
set -euo pipefail

cd "$(dirname "$0")/wrapper"

SDK=/opt/android-sdk
# v1.6.5 — on ARM64 container hosts the Google-provided x86_64 build-tools
# binaries (aapt/zipalign/apksigner) won't execute; prefer Debian's apt-shipped
# native arm64 binaries from /usr/bin. The Google android.jar is arch-agnostic.
DEB_BT=/usr/bin
PLATFORM=$SDK/platforms/android-34/android.jar
D8_JAR=$SDK/build-tools/34.0.0/lib/d8.jar
VERSION="${VERSION:-1.7.5}"
FLAVOR="${FLAVOR:-nodepro}"

case "$FLAVOR" in
    light)   PKG="io.sanctara.light";   OUT_NAME="sanctara-light.apk";   NATIVE_REQUIRED=0; ADMOB_ON=1 ;;
    nodepro) PKG="io.sanctara.nodepro"; OUT_NAME="sanctara-node-pro.apk"; NATIVE_REQUIRED=1; ADMOB_ON=0 ;;
    *)       echo "[FATAL] Unknown FLAVOR='$FLAVOR' (expected: light | nodepro)" >&2; exit 2 ;;
esac
# Auto-detect repo root so the same script works on the dev container (/app)
# AND on GitHub Actions runners (/home/runner/work/<repo>/<repo>).
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DEST="${REPO_ROOT}/frontend/public/${OUT_NAME}"
mkdir -p "${REPO_ROOT}/frontend/public"

# v1.3.7 — bundle librandomx.so when the GitHub Actions artifact is present.
# Path: /app/android-client/wrapper/jniLibs/arm64-v8a/librandomx.so
JNI_DIR="$(pwd)/jniLibs"
NATIVE_LIB="${JNI_DIR}/arm64-v8a/librandomx.so"

rm -rf build/classes build/gen build/grid-*.apk build/classes.dex build/lib
mkdir -p build/classes build/gen

# v1.7.5 — write a flavor-aware AndroidManifest.xml each build so both APKs
# can co-exist on the same device with distinct package names.
VERSION_CODE="$(echo "$VERSION" | awk -F. '{ printf "%d%02d%02d", $1, $2, $3 }')"
APP_LABEL_LIGHT="Sanctara Light"
APP_LABEL_NODEPRO="Sanctara Node Pro"
case "$FLAVOR" in light) LABEL="$APP_LABEL_LIGHT" ;; *) LABEL="$APP_LABEL_NODEPRO" ;; esac

# Use a templated manifest if present, otherwise patch the existing one in-place.
if [ -f AndroidManifest.template.xml ]; then
    sed -e "s|@@PACKAGE@@|${PKG}|g" \
        -e "s|@@VERSION_CODE@@|${VERSION_CODE}|g" \
        -e "s|@@VERSION_NAME@@|${VERSION}|g" \
        -e "s|@@APP_LABEL@@|${LABEL}|g" \
        AndroidManifest.template.xml > AndroidManifest.xml
else
    sed -i -E "s|android:versionCode=\"[0-9]+\"|android:versionCode=\"${VERSION_CODE}\"|" AndroidManifest.xml
    sed -i -E "s|android:versionName=\"[^\"]+\"|android:versionName=\"${VERSION}\"|"     AndroidManifest.xml
    sed -i -E "s|package=\"[^\"]+\"|package=\"${PKG}\"|"                                  AndroidManifest.xml
fi
echo "[+] flavor=${FLAVOR} package=${PKG} version=${VERSION} versionCode=${VERSION_CODE}"

# v1.7.5 — generate BuildConfig.java carrying flavor + AdMob switch into the
# Java source tree so Java code can branch on it at compile time.
mkdir -p build/gen/io/thegrid/worker
cat > build/gen/io/thegrid/worker/BuildConfig.java <<EOF
package io.thegrid.worker;

/** Auto-generated by build-apk.sh — do not edit. */
public final class BuildConfig {
    private BuildConfig() {}
    public static final String FLAVOR         = "${FLAVOR}";
    public static final String VERSION_NAME   = "${VERSION}";
    public static final int    VERSION_CODE   = ${VERSION_CODE};
    public static final boolean ADMOB_ENABLED = $([ "$ADMOB_ON" -eq 1 ] && echo "true" || echo "false");
    public static final boolean NATIVE_MINING = $([ "$NATIVE_REQUIRED" -eq 1 ] && echo "true" || echo "false");
}
EOF

# 1. compile resources
$DEB_BT/aapt package -f -M AndroidManifest.xml -S res \
    -I "$PLATFORM" \
    -F build/grid-unaligned.apk -J build/gen
[ -f build/gen/R.java ] && mv build/gen/R.java build/gen/io/thegrid/worker/R.java || true

# 2. compile Java
# v1.7.5 — RewardedAdManager.java is included for both flavors so MainActivity
# compiles. At runtime, BuildConfig.ADMOB_ENABLED=false short-circuits ad calls
# for Node Pro builds.
JAVA_SOURCES=$(ls src/io/thegrid/worker/*.java)

# v1.7.5 — optional AdMob SDK classpath. Light builds can bundle the Google
# Play Services Ads SDK by exporting ADMOB_SDK_CP="path/to/play-services-ads.jar:..."
# before invoking this script. When omitted, RewardedAdManager falls back to
# reflection at runtime (and serves a Google test ID via the backend).
ADMOB_CP=""
if [ "$ADMOB_ON" -eq 1 ] && [ -n "${ADMOB_SDK_CP:-}" ]; then
    ADMOB_CP=":${ADMOB_SDK_CP}"
    echo "[+] AdMob SDK classpath attached for Light build"
fi

javac -source 1.8 -target 1.8 -d build/classes \
    -cp "${PLATFORM}${ADMOB_CP}" \
    $JAVA_SOURCES \
    build/gen/io/thegrid/worker/R.java \
    build/gen/io/thegrid/worker/BuildConfig.java

# 3. DEX
java -cp "$D8_JAR" com.android.tools.r8.D8 \
    --release --min-api 24 \
    --lib "$PLATFORM" \
    --output build/ $(find build/classes -name "*.class")

# 4. Add classes.dex to APK
cp build/grid-unaligned.apk build/grid-with-dex.apk
( cd build && zip -j -q grid-with-dex.apk classes.dex )

# 4b. Native library handling.
NATIVE_FLAG="OFF"
NATIVE_SHA="-"
if [ "$NATIVE_REQUIRED" -eq 1 ]; then
    if [ ! -f "$NATIVE_LIB" ]; then
        cat <<EOF >&2

[FATAL] Node Pro build aborted — librandomx.so missing.

Expected path:
    $NATIVE_LIB

Produce it via:
    1. Save to GitHub.
    2. Run the "build-librandomx-android-arm64" workflow.
    3. Download librandomx-arm64-v8a artifact, unzip into the path above.

EOF
        exit 99
    fi
    echo "[+] embedding librandomx.so ($(stat --format=%s "$NATIVE_LIB") bytes)"
    mkdir -p build/lib/arm64-v8a
    cp "$NATIVE_LIB" build/lib/arm64-v8a/librandomx.so
    # Use python zipfile to embed the .so UNCOMPRESSED — required by Android
    # for native libs (so they can be mmap'd directly). The 'zip' CLI silently
    # refused to update aapt-produced APKs in v1.7.x → APK shipped without the
    # library and devices fell back to the 2 H/s placeholder path.
    python3 - "build/grid-with-dex.apk" "build/lib/arm64-v8a/librandomx.so" "lib/arm64-v8a/librandomx.so" <<'PYEOF'
import sys, zipfile, os
apk_path, lib_src, arc_name = sys.argv[1], sys.argv[2], sys.argv[3]
with zipfile.ZipFile(apk_path, 'r') as zin:
    entries = [(i, zin.read(i.filename)) for i in zin.infolist() if i.filename != arc_name]
with zipfile.ZipFile(apk_path, 'w', zipfile.ZIP_STORED) as zout:
    for info, data in entries:
        new_info = zipfile.ZipInfo(filename=info.filename, date_time=info.date_time)
        new_info.compress_type = info.compress_type
        new_info.external_attr = info.external_attr
        zout.writestr(new_info, data)
    with open(lib_src, 'rb') as f:
        ni = zipfile.ZipInfo(arc_name)
        ni.compress_type = zipfile.ZIP_STORED
        ni.external_attr = 0o644 << 16
        zout.writestr(ni, f.read())
print(f"[+] embedded {arc_name} into APK ({os.path.getsize(apk_path)} bytes total)")
PYEOF
    # Sanity-check: refuse to continue if librandomx.so somehow didn't land.
    if ! unzip -l build/grid-with-dex.apk 2>/dev/null | grep -q "lib/arm64-v8a/librandomx.so"; then
        echo "[FATAL] librandomx.so missing from APK after embedding!" >&2
        unzip -l build/grid-with-dex.apk >&2 || true
        exit 98
    fi
    NATIVE_FLAG="ON"
    NATIVE_SHA=$(sha256sum build/lib/arm64-v8a/librandomx.so | cut -d' ' -f1)
    echo "[+] native lib SHA-256: $NATIVE_SHA"
else
    echo "[+] flavor=light — native library intentionally omitted"
fi

# 5. Align
$DEB_BT/zipalign -p -f 4 build/grid-with-dex.apk build/grid-aligned.apk

# 6. Sign with debug keystore (create if missing)
KS=build/debug.keystore
if [ ! -f "$KS" ]; then
    keytool -genkey -v \
        -keystore "$KS" \
        -storepass android -keypass android \
        -alias androiddebugkey -dname "CN=Android Debug,O=Android,C=US" \
        -keyalg RSA -keysize 2048 -validity 10000 >/dev/null 2>&1
fi

$DEB_BT/apksigner sign \
    --ks "$KS" --ks-key-alias androiddebugkey \
    --ks-pass pass:android --key-pass pass:android \
    --v1-signing-enabled true --v2-signing-enabled true --v3-signing-enabled true \
    --out "build/${OUT_NAME}" build/grid-aligned.apk

$DEB_BT/apksigner verify -v "build/${OUT_NAME}" >/dev/null
cp -f "build/${OUT_NAME}" "$OUT_DEST"

SIZE=$(stat --format=%s "$OUT_DEST")
SHA=$(sha256sum "$OUT_DEST" | cut -d' ' -f1)
echo
echo "=== APK BUILD OK ==="
echo "File   : $OUT_DEST"
echo "Flavor : $FLAVOR"
echo "Package: $PKG"
echo "Version: $VERSION"
echo "Native : $NATIVE_FLAG"
echo "AdMob  : $([ "$ADMOB_ON" -eq 1 ] && echo "ENABLED (test ID)" || echo "disabled")"
echo "Size   : $SIZE bytes"
echo "SHA-256: $SHA"
